/*
 * This source file was generated by the Gradle 'init' task
 */
package persistence;

import lombok.AllArgsConstructor;
import persistence.migration.MigrationStrategy;

import java.sql.SQLException;

import static persistence.config.ConnectioConfig.getConnection;


@AllArgsConstructor
public class Main {

    public static void main(String[] args) throws SQLException {
        try( var connection = getConnection()){
            new MigrationStrategy(connection).executeMigration();
        }
    }
}
