/*
 * This source file was generated by the Gradle 'init' task
 */
package br.com.dio;

import lombok.AllArgsConstructor;

@AllArgsConstructor
public class App {
    public static void main(String[] args) {

    }
}
