/*
 * This source file was generated by the Gradle 'init' task
 */
package br.com.dio;

import lombok.AllArgsConstructor;
import br.com.dio.persistence.migration.MigrationStrategy;
import br.com.dio.ui.MainMenu;

import java.sql.SQLException;

import static br.com.dio.persistence.config.ConnectioConfig.getConnection;


@AllArgsConstructor
public class Main {

    public static void main(String[] args) throws SQLException {
        try( var connection = getConnection()){
            new MigrationStrategy(connection).executeMigration();
        }
        new MainMenu().execute();
    }
}
